version: '3.8'


networks:
  ft_transcendence:
    driver: bridge

services:

  postgres:
    image: postgres:latest
    container_name: postgres
    env_file:
      - .env
    volumes:
      - /var/lib/postgresql/data
    restart: always
    networks:
      - ft_transcendence
    expose:
      - 5432

  react:
    hostname: react
    image: react:image
    container_name: react
    build:
      context: frontend
      dockerfile: Dockerfile
    volumes:
      - /app
    env_file:
      - .env
    depends_on:
      - nestjs
    restart: always
    networks:
      - ft_transcendence
    expose:
      - 5173
    ports:
      - 5173:5173

  nestjs:
    hostname: nestjs
    image: nestjs:image
    container_name: nestjs
    build:
      context: backend
      dockerfile: Dockerfile
    volumes:
      - /app
    env_file:
      - .env
    depends_on:
      - postgres
    restart: always
    networks:
      - ft_transcendence
    expose:
      - 3000
    ports:
      - 3000:3000

